version: "3.9"

services:
  api:
    image: vitoriarsm/projetodevops-api:${IMAGE_TAG}
    container_name: flask_api
    ports:
      - "5000:5000"
    environment:
      - DB_HOST=postgres_db
      - DB_USER=postgres
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=meubanco
    depends_on:
      - postgres

  postgres:
    image: postgres:15-alpine
    container_name: postgres_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: meubanco
    volumes:
      - postgresdata:/var/lib/postgresql/data

volumes:
  postgresdata:
